"""Emit assets/data.js for the web pages from the shared profile definitions.

    python3 tools/gen_data.py

Writes into this repo's assets/ directory. B360_WEB overrides the destination if you
ever need to generate into a checkout somewhere else.
"""
import sys
sys.dont_write_bytecode = True          # no stray __pycache__ in the repo

import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from assessment_content import (PROFILES, ROSTER, RELATIONSHIPS, SCALE_NOTES,
                                RELATIONSHIP_MAP, validate, coverage_warnings)

WEB = os.environ.get("B360_WEB", os.path.dirname(HERE))


def pack(p):
    return {
        "id": p["id"], "label": p["label"],
        "formTitle": p["formTitle"], "consoleTitle": p["consoleTitle"],
        "blurb": p.get("blurb", ""), "note": p.get("note", ""),
        "relationships": p["relationships"],
        "dimensions": [{"code": c, "name": n, "question": q} for c, n, q in p["dimensions"]],
        "items": [{"code": c, "text": t, "importance": i, "dim": c[0]} for c, t, i in p["items"]],
        "metrics": {k: {"metric": v[0], "target": v[1], "source": v[2], "cadence": v[3]}
                    for k, v in p["metrics"].items()},
        "scale": [{"value": v, "name": nm, "desc": ds} for v, nm, ds in p["scale"]],
        "openQuestions": p["openQuestions"],
    }


errs = validate()
if errs:
    print("VALIDATION FAILED — not writing data.js:")
    for e in errs:
        print("  -", e)
    raise SystemExit(1)
for w in coverage_warnings():
    print("note:", w)

data = {
    "version": "2",
    "roster": [{"name": r["name"], "role": r["role"], "profile": r["profile"]} for r in ROSTER],
    "relationships": [[k, l] for k, l in RELATIONSHIPS],
    "profiles": {k: pack(v) for k, v in PROFILES.items()},
    "scaleNotes": [{"label": l, "text": t} for l, t in SCALE_NOTES],
    "relationshipMap": RELATIONSHIP_MAP,
    "contact": "bryan@blossom.ag",
}

out = os.path.join(WEB, "assets", "data.js")
if not os.path.isdir(os.path.dirname(out)):
    raise SystemExit(f"no assets/ directory at {WEB} — set B360_WEB to the web repo")
with open(out, "w") as f:
    f.write("/* Generated by gen_data.py from assessment_content.py — do not edit by hand. */\n")
    f.write("window.B360_DATA = " + json.dumps(data, indent=2, ensure_ascii=False) + ";\n")
print("wrote", out)
for k, v in data["profiles"].items():
    imp = {}
    for it in v["items"]:
        imp[it["importance"]] = imp.get(it["importance"], 0) + 1
    print(f"  profile '{k}': {len(v['items'])} items, importance {dict(sorted(imp.items()))}")
for r in data["roster"]:
    print(f"  {r['name']:8s} {r['role'] or '(role not set)':34s} -> {r['profile'] or '(no profile)'}")
